name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 1
      - name: Publish GitHub action
        uses: dylanvann/publish-github-action@v1.1.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
