name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1
      - name: Set up node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Yarn deduplicate
        run: yarn run yarn-deduplicate --fail --strategy fewer
      - name: Yarn build
        run: yarn run build
      - name: Yarn prettier
        run: yarn run prettier --check --end-of-line auto
      - name: Yarn xo
        run: yarn run xo
      # Optional integration test of the action using a dedicated GitHub App.
      - name: Generate token
        id: generate_token
        if: vars.TEST_GITHUB_APP_ID != ''
        uses: ./
        with:
          # The only required permission is `Repository permissions > Metadata: Read-only`.
          app_id: ${{ vars.TEST_GITHUB_APP_ID }}
          private_key: ${{ secrets.TEST_GITHUB_APP_PRIVATE_KEY }}
      - name: Check token length
        if: steps.generate_token.outcome != 'skipped'
        run: node --eval "assert('${{ steps.generate_token.outputs.token }}'.length > 0);"
